// web/src/shared/ui/chip.vue
<script setup lang="ts">
defineProps<{
  title: string
  selected?: boolean
  disabled?: boolean
}>()
const emit = defineEmits<{ (e: 'select'): void }>()
</script>

<template>
  <button class="chip" :class="{ selected }" :disabled="disabled" @click="emit('select')">{{ title }}</button>
</template>

<style lang="scss">
.chip {
  border: 1px solid var(--secondaryBackground);
  border-radius: 20px;
  color: var(--secondary);
  cursor: pointer;
  margin-left: 8px;
  padding: 4px 12px;
  font-size: 14px;

  &.selected {
    background-color: var(--searchBackground);
    border-color: var(--searchSelected);
    color: var(--searchText);
  }
}
</style>

// src/shared/ui/chip.tsx
import React, { FC } from 'react'
import { Text, TouchableBox } from 'shared/ui/theme'

type Props = {
  title: string
  selected?: boolean
  onPress?: () => void
  disabled?: boolean
}

export const Chip: FC<Props> = ({ title, selected, disabled, onPress }) => {
  return (
    <TouchableBox
      px={2}
      py={1}
      ml={2}
      borderColor={selected ? 'searchSelected' : 'secondaryBackground'}
      backgroundColor={selected ? 'searchBackground' : null}
      borderRadius={20}
      borderWidth={1}
      disabled={disabled}
      onPress={onPress}
      testID={title}
    >
      <Text variant='chip' color={selected ? 'searchText' : 'secondary'} testID={selected ? 'selected' : null}>
        {title}
      </Text>
    </TouchableBox>
  )
}
