// web/src/entities/book/ui/book-item.vue
<script setup lang="ts">
import type { BookItem } from 'shared/api'
import { FileIcon, Item } from 'shared/ui'

const { book } = defineProps<{ book: BookItem }>()

const emit = defineEmits<{
  (e: 'download'): void
}>()

const subtitle = [book.size, book.lang, book.translation].filter(p => p).join(', ')
const ext = book.ext.replace('.zip', '')
</script>

<template>
  <Item :suptitle="book.authors" :title="book.title" :subtitle="subtitle" @click="emit('download')">
    <template v-slot:icon>
      <FileIcon :text="ext" />
    </template>
  </Item>
</template>

// web/src/entities/book/ui/book-item.tsx
import type { Component } from 'solid-js'
import type { BookItem as IBookItem } from 'shared/api'
import { FileIcon, Item } from 'shared/ui'

interface Props {
  book: IBookItem
  onDownload: () => void
}

export const BookItem: Component<Props> = props => {
  return (
    <Item
      suptitle={props.book.authors}
      title={props.book.title}
      subtitle={[props.book.size, props.book.lang, props.book.translation].filter(p => p).join(', ')}
      onClick={props.onDownload}
      icon={<FileIcon text={props.book.ext.replace('.zip', '')} />}
    />
  )
}
