// src/entities/book/ui/book-item.tsx
import React, { FC } from 'react'

import { BookItem as IBookItem } from 'shared/api'
import { FileIcon, Item } from 'shared/ui'

interface Props {
  item: IBookItem
  onPress: (item: IBookItem) => void
}

export const BookItem: FC<Props> = ({ item, onPress }) => {
  const other = [item.size, item.lang, item.translation].filter(p => p).join(', ')
  const ext = item.ext.replace('.zip', '')

  return (
    <Item mb={3} onPress={() => onPress(item)} testID='book-item'>
      <FileIcon size={40} color='searchSelected' text={ext} />

      <Item.Text suptitle={item.authors} title={item.title} subtitle={other} />
    </Item>
  )
}

// web/src/entities/book/ui/book-item.tsx
import type { Component } from 'solid-js'
import type { BookItem as IBookItem } from 'shared/api'
import { FileIcon, Item } from 'shared/ui'

interface Props {
  book: IBookItem
  onDownload: () => void
}

export const BookItem: Component<Props> = props => {
  return (
    <Item
      suptitle={props.book.authors}
      title={props.book.title}
      subtitle={[props.book.size, props.book.lang, props.book.translation].filter(p => p).join(', ')}
      onClick={props.onDownload}
      icon={<FileIcon text={props.book.ext.replace('.zip', '')} />}
    />
  )
}
