// web/src/shared/ui/input.tsx
import { Component, Show, JSXElement } from 'solid-js'
import { CloseIcon } from './icons'

interface Props {
  value: string
  onChange: (value: string) => void
  placeholder?: string
  disabled?: boolean
  type?: string
  icon?: JSXElement
  role?: any
}

export const Input: Component<Props> = props => {
  return (
    <div class='input flex relative items-center'>
      <span class='absolute inset-y-0 left-0 flex items-center pl-2' v-if='$slots.icon'>
        <Show when={!!props.icon}>{props.icon}</Show>
      </span>

      <input
        class='flex-1 py-2 rounded-md pl-10'
        placeholder={props.placeholder}
        value={props.value}
        type={props.type}
        disabled={props.disabled}
        onChange={(e: any) => props.onChange(e.target.value)}
        role={props.role}
      />

      <Show when={props.value && !props.disabled}>
        <div class='cursor-pointer px-2 z-10' onClick={() => props.onChange('')}>
          <CloseIcon />
        </div>
      </Show>
    </div>
  )
}

// web/src/shared/ui/input.vue
<script lang="ts" setup>
defineProps<{
  value: string
  placeholder?: string
  disabled?: boolean
  type?: string
}>()
const emit = defineEmits(['update:value'])

const change = (value: string) => emit('update:value', value)
</script>

<template>
  <div class="input flex relative items-center">
    <span class="absolute inset-y-0 left-0 flex items-center pl-2" v-if="$slots.icon">
      <slot name="icon"></slot>
    </span>

    <input
      class="flex-1 py-2 rounded-md pl-10"
      :placeholder="placeholder"
      :value="value"
      :type="type"
      :disabled="disabled"
      @change="change($event.target.value)"
    />

    <div class="cursor-pointer px-2 z-10" v-if="value && !disabled" @click="change('')">
      <svg viewBox="0 0 320 512" width="24" height="24">
        <path
          fill="var(--deleteButton)"
          d="M207.6 256l107.72-107.72c6.23-6.23 6.23-16.34 0-22.58l-25.03-25.03c-6.23-6.23-16.34-6.23-22.58 0L160 208.4 52.28 100.68c-6.23-6.23-16.34-6.23-22.58 0L4.68 125.7c-6.23 6.23-6.23 16.34 0 22.58L112.4 256 4.68 363.72c-6.23 6.23-6.23 16.34 0 22.58l25.03 25.03c6.23 6.23 16.34 6.23 22.58 0L160 303.6l107.72 107.72c6.23 6.23 16.34 6.23 22.58 0l25.03-25.03c6.23-6.23 6.23-16.34 0-22.58L207.6 256z"
        ></path>
      </svg>
    </div>
  </div>
</template>

<style>
.input {
  background: #ffffff;
  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.25);
  border-radius: 10px;
  padding-left: 4px;
}
</style>
