// web/src/shared/ui/item.tsx
import { Component, Show, JSXElement } from 'solid-js'

interface Props {
  suptitle?: string
  title: string
  subtitle?: string
  onClick(): void
  icon: JSXElement
}

export const Item: Component<Props> = props => {
  return (
    <div class='flex flex-row items-center cursor-pointer' onClick={props.onClick}>
      <Show when={!!props.icon}>
        <div class='mr-1'>{props.icon}</div>
      </Show>

      <div class='flex-1'>
        <Show when={props.suptitle}>
          <div class='text-xs text-secondary'>{props.suptitle}</div>
        </Show>

        <div class='text-primary'>{props.title}</div>

        <Show when={props.subtitle}>
          <div class='text-xs text-secondary'>{props.subtitle}</div>
        </Show>
      </div>
    </div>
  )
}

// web/src/shared/ui/item.vue
<script setup lang="ts">
import { useSlots } from 'vue'

defineProps<{
  suptitle?: string
  title: string
  subtitle?: string
}>()
const emit = defineEmits<{
  (e: 'click'): void
}>()

const slots = useSlots()
</script>

<template>
  <div class="flex flex-row items-center cursor-pointer" @click="emit('click')">
    <div v-if="slots.icon" class="mr-1">
      <slot name="icon" />
    </div>

    <div class="flex-1">
      <div v-if="suptitle" class="text-xs text-secondary">
        {{ suptitle }}
      </div>

      <div class="text-primary">
        {{ title }}
      </div>

      <div v-if="subtitle" class="text-xs text-secondary">
        {{ subtitle }}
      </div>
    </div>
  </div>
</template>
