// web/src/spinner.svelte
<script>
  export let size = 32;
  export let color = '#FF3E00';
  export let unit = 'px';
</script>

<style>
  .circle {
    height: var(--size);
    width: var(--size);
    border-color: var(--color) transparent var(--color) var(--color);
    border-width: calc(var(--size) / 15);
    border-style: solid;
    border-image: initial;
    border-radius: 50%;
    animation: 0.75s linear 0s infinite normal none running rotate;
  }
  @keyframes rotate {
    0% {
      transform: rotate(0);
    }
    100% {
      transform: rotate(360deg);
    }
  }
</style>

<div class="circle" style="--size: {size}{unit}; --color: {color};" />

// web/src/shared/ui/spinner.vue
<template>
  <div class="circle" />
</template>

<style>
.circle {
  align-self: center;
  animation: 0.75s linear 0s infinite normal none running rotate;
  border-color: var(--searchSelected) transparent var(--searchSelected) var(--searchSelected);
  border-width: 2px;
  border-style: solid;
  border-image: initial;
  border-radius: 50%;
  height: 32px;
  margin-top: 32px;
  width: 32px;
}
@keyframes rotate {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>
