// web/src/pages/login-page.vue
<script setup lang="ts">
import { setCookie } from 'features/auth'
import { api } from 'shared/api'
import { Input, EmailIcon, KeyIcon } from 'shared/ui'
import Button from 'shared/ui/button.vue'

let email = $ref(import.meta.env.VITE_INITIAL_EMAIL)
let password = $ref(import.meta.env.VITE_INITIAL_PASSWORD)
let inProgress = $ref(false)

const login = async () => {
  if (!email || !password) {
    return
  }

  inProgress = true

  try {
    const cookie = await api.sendLogin(email, password)

    setCookie(cookie)
  } catch (e) {
    alert(e)
  }

  inProgress = false
}
</script>

<template>
  <div class="pt-4 px-4">
    <h1>Login</h1>

    <form class="mt-4" @submit.prevent="login">
      <Input v-model:value="email" placeholder="E-Mail" :disabled="inProgress">
        <template v-slot:icon>
          <EmailIcon />
        </template>
      </Input>

      <div class="mt-2">
        <Input v-model:value="password" type="password" placeholder="Password" :disabled="inProgress">
          <template v-slot:icon>
            <KeyIcon />
          </template>
        </Input>
      </div>

      <div class="mt-4 text-center">
        <Button type="submit" :disabled="inProgress">Login</Button>
      </div>
    </form>
  </div>
</template>

// web/src/pages/login-page/login-page.tsx
import { Component, createSignal, Show } from 'solid-js'
import { Button, Input, EmailIcon, KeyIcon, Spinner } from 'shared/ui'
import { useSignal } from 'shared/lib/solid-nanostore'
import { $inProgress, login } from './login-page-model'

export const LoginPage: Component = () => {
  const [email, setEmail] = createSignal(import.meta.env.VITE_INITIAL_EMAIL)
  const [password, setPassword] = createSignal(import.meta.env.VITE_INITIAL_PASSWORD)
  const inProgress = useSignal($inProgress)

  const onSubmit = async (e: Event) => {
    e.preventDefault()

    login(email(), password())
  }

  return (
    <div class='pt-4 px-4'>
      <h1>Login</h1>

      <form class='mt-4' onSubmit={onSubmit}>
        <Input
          name='email'
          value={email()}
          onChange={setEmail}
          placeholder='E-Mail'
          disabled={inProgress()}
          icon={<EmailIcon />}
          role='textbox'
        />

        <div class='mt-2'>
          <Input
            name='password'
            value={password()}
            onChange={setPassword}
            placeholder='Password'
            disabled={inProgress()}
            type='password'
            icon={<KeyIcon />}
            role='textbox'
          />
        </div>

        <div class='mt-4 text-center'>
          <Show when={!inProgress()} fallback={<Spinner />}>
            <Button type='submit' disabled={inProgress()}>
              Login
            </Button>
          </Show>
        </div>
      </form>
    </div>
  )
}
