// src/entities/search-filters/ui/search-chips.tsx
import React, { FC } from 'react'
import { ScrollView, StyleSheet, View } from 'react-native'
import { useStore } from 'effector-react'

import { Chip } from 'shared/ui'

import { $searchFilters, setEpub, setFb2, setFlibusta, setZLib } from '../model'

interface Props {
  disabled?: boolean
}

export const SearchChips: FC<Props> = ({ disabled }) => {
  const { extension, type } = useStore($searchFilters)
  const isZLib = type === 'ZLIB'

  return (
    <ScrollView horizontal keyboardShouldPersistTaps='always'>
      <Chip title='Z-Library' selected={type === 'ZLIB'} onPress={setZLib} disabled={disabled} />
      <Chip title='Flibusta' selected={type === 'FLIBUSTA'} onPress={setFlibusta} disabled={disabled} />

      <View style={s.placeholder} />

      {isZLib && <Chip title='EPUB' selected={extension === 'epub'} onPress={setEpub} disabled={disabled} />}
      {isZLib && <Chip title='FB2' selected={extension === 'fb2'} onPress={setFb2} disabled={disabled} />}
    </ScrollView>
  )
}

const s = StyleSheet.create({
  placeholder: { width: 20 },
})

// web/src/features/filters/ui/search-chips.vue
<script lang="ts" setup>
import { useStore } from '@nanostores/vue'
import { Chip } from 'shared/ui'
import { $ext, $source } from '../model'

const source = useStore($source)
const ext = useStore($ext)
</script>

<template>
  <Chip title="Flibusta" :selected="source === 'FLIBUSTA'" @select="$source.set('FLIBUSTA')" />
  <Chip title="ZLib" :selected="source === 'ZLIB'" @select="$source.set('ZLIB')" />

  <template v-if="source === 'ZLIB'">
    <div class="w-4" />

    <Chip title="EPUB" :selected="ext === 'epub'" @select="$ext.set('epub')" />
    <Chip title="FB2" :selected="ext === 'fb2'" @select="$ext.set('fb2')" />
    <Chip title="PDF" :selected="ext === 'pdf'" @select="$ext.set('pdf')" />
  </template>
</template>
