// web/src/features/filters/ui/search-chips.vue
<script lang="ts" setup>
import { useStore } from '@nanostores/vue'
import { Chip } from 'shared/ui'
import { $ext, $source } from '../model'

const source = useStore($source)
const ext = useStore($ext)
</script>

<template>
  <Chip title="Flibusta" :selected="source === 'FLIBUSTA'" @select="$source.set('FLIBUSTA')" />
  <Chip title="ZLib" :selected="source === 'ZLIB'" @select="$source.set('ZLIB')" />

  <template v-if="source === 'ZLIB'">
    <div class="w-4" />

    <Chip title="EPUB" :selected="ext === 'epub'" @select="$ext.set('epub')" />
    <Chip title="FB2" :selected="ext === 'fb2'" @select="$ext.set('fb2')" />
    <Chip title="PDF" :selected="ext === 'pdf'" @select="$ext.set('pdf')" />
  </template>
</template>

// web/src/features/filters/ui/search-chips.tsx
import { Component, Show } from 'solid-js'
import { useSignal } from 'shared/lib/solid-nanostore'
import { Chip } from 'shared/ui'
import { $ext, $source } from '../model'

export const SearchChips: Component = () => {
  const source = useSignal($source)
  const ext = useSignal($ext)

  return (
    <>
      <Chip title='Flibusta' selected={source() === 'FLIBUSTA'} onSelect={() => $source.set('FLIBUSTA')} />
      <Chip title='ZLib' selected={source() === 'ZLIB'} onSelect={() => $source.set('ZLIB')} />

      <Show when={source() === 'ZLIB'}>
        <div class='w-4' />

        <Chip title='EPUB' selected={ext() === 'epub'} onSelect={() => $ext.set('epub')} />
        <Chip title='FB2' selected={ext() === 'fb2'} onSelect={() => $ext.set('fb2')} />
        <Chip title='PDF' selected={ext() === 'pdf'} onSelect={() => $ext.set('pdf')} />
      </Show>
    </>
  )
}
