// web/src/app/App.vue
<script setup lang="ts">
import { useStore } from '@nanostores/vue'

import SearchPage from 'pages/search-page/search-page.vue'
import LoginPage from 'pages/login-page.vue'
import { $showLogin } from './app-model'

const showLogin = useStore($showLogin)
</script>

<template>
  <component :is="showLogin ? LoginPage : SearchPage" />
</template>

<style>
#app {
  height: 100vh;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}
</style>

// web/src/app/app.tsx
import type { Component } from 'solid-js'
import { Dynamic } from 'solid-js/web'

import { useSignal } from 'shared/lib/solid-nanostore'
import { SearchPage } from 'pages/search-page'
import { LoginPage } from 'pages/login-page'

import { $showLogin } from './app-model'

export const App: Component = () => {
  const showLogin = useSignal($showLogin)

  return <Dynamic component={showLogin() ? LoginPage : SearchPage} />
}
