// web/src/pages/login-page.tsx
import { Component, createSignal } from 'solid-js'
import { setCookie } from 'features/auth'
import { api } from 'shared/api'
import { Button, Input, EmailIcon, KeyIcon } from 'shared/ui'

export const LoginPage: Component = () => {
  const [email, setEmail] = createSignal(import.meta.env.VITE_INITIAL_EMAIL)
  const [password, setPassword] = createSignal(import.meta.env.VITE_INITIAL_PASSWORD)
  const [inProgress, setInProgress] = createSignal(false)

  const login = async (e: Event) => {
    e.preventDefault()

    if (!email || !password) {
      return
    }

    setInProgress(true)

    try {
      const cookie = await api.sendLogin(email(), password())

      setCookie(cookie)
    } catch (e) {
      alert(e)
    }

    setInProgress(false)
  }

  return (
    <div class='pt-4 px-4'>
      <h1>Login</h1>

      <form class='mt-4' onSubmit={login}>
        <Input value={email()} onChange={setEmail} placeholder='E-Mail' disabled={inProgress()} icon={<EmailIcon />} />

        <div class='mt-2'>
          <Input
            value={password()}
            onChange={setPassword}
            placeholder='Password'
            disabled={inProgress()}
            type='password'
            icon={<KeyIcon />}
          />
        </div>

        <div class='mt-4 text-center'>
          <Button type='submit' disabled={inProgress()}>
            Login
          </Button>
        </div>
      </form>
    </div>
  )
}

// web/src/pages/login-page.vue
<script setup lang="ts">
import { setCookie } from 'features/auth'
import { api } from 'shared/api'
import { Input, EmailIcon, KeyIcon } from 'shared/ui'
import Button from 'shared/ui/button.vue'

let email = $ref(import.meta.env.VITE_INITIAL_EMAIL)
let password = $ref(import.meta.env.VITE_INITIAL_PASSWORD)
let inProgress = $ref(false)

const login = async () => {
  if (!email || !password) {
    return
  }

  inProgress = true

  try {
    const cookie = await api.sendLogin(email, password)

    setCookie(cookie)
  } catch (e) {
    alert(e)
  }

  inProgress = false
}
</script>

<template>
  <div class="pt-4 px-4">
    <h1>Login</h1>

    <form class="mt-4" @submit.prevent="login">
      <Input v-model:value="email" placeholder="E-Mail" :disabled="inProgress">
        <template v-slot:icon>
          <EmailIcon />
        </template>
      </Input>

      <div class="mt-2">
        <Input v-model:value="password" type="password" placeholder="Password" :disabled="inProgress">
          <template v-slot:icon>
            <KeyIcon />
          </template>
        </Input>
      </div>

      <div class="mt-4 text-center">
        <Button type="submit" :disabled="inProgress">Login</Button>
      </div>
    </form>
  </div>
</template>
